### ISSUE TITLE
@SuperBuilder will ignore the initializing expression entirely. ... 에러 발생

### ISSUE THREAD

**Issue by eod940** [ValueWith/ValueWith_BE#13]
**이슈 사항**
1. 문제점 발생
이메일 테스트 빌드 중 @SuperBuilder will ignore the initializing expression entirely... 에러가 발생했습니다.
아래 첨부된 사진 확인해 주세요
<img width="800" alt="Screenshot 2023-10-27 at 3 19 01 PM" src="https://github.com/ValueWith/ValueWith_BE/assets/51254234/6ec726e6-964e-48cf-9c0e-1f4dbc07867f">

엔티티 관련해 건드린게 없는데 발생했습니다. **추후에 문제가 될 수도 있을까요?**

2. 해결 방안
다시 빌드하니 해당 에러가 사라졌습니다.
---

**배경**
1. 어느 환경(배경)에서 문제가 발생했는지 간략히 적어주세요. 
h2

**Comment by dodunge** [comment]
에러 내용을 보니까 @Builder는 초기화를 완전히 무시한다고 쓰여 있고, 초기화 해야 하는 필드가 존재할 때 @Builder.Default 를 사용하거나 아니면 final 쓰면된다고 쓰여 있습니다.
따라서 isDeleded를 false로 초기화 해두었고, List<>로 설정해준 필드들은 = new ArrayList<>로 초기화 해주었기 때문에 해당 에러 메시지가 뜬 것 같습니다.
따라서 @SuperBuilder를 사용하는 entity의 초기화되는 필드들 위에 @Builder.Default혹은 final을 사용해서 해결해 주어야 할 것 같아요!!
