### ISSUE TITLE
유저가 채팅룸을 조회하면 들어가지 않은 채팅룸이 조회되는 현상

### ISSUE THREAD

**Issue by eod940** [ValueWith/ValueWith_BE#139]
**이슈 사항**
유저가 채팅룸을 조회하면 들어가지 않았던 채팅룸이 조회됩니다.

- 현재 [유진] 유저의 경우 [부산 여행...] 채팅룸에 있어야 합니다. 하지만 채팅룸 조회시 [경주 나들이...] 채팅룸이 조회됩니다.
- 현재 [트위버] 유저의 경우 [대구 이월드...] 채팅룸에 있어야 합니다. 하지만 채팅룸 조회시 [경주 나들이...] 채팅룸이 조회됩니다.
- 현재 [개발자 루피] 유저의 경우 채팅룸을 조회하면 요청실패가 뜹니다.

---

**배경**
1. 어느 환경(배경)에서 문제가 발생했는지 간략히 적어주세요. (e.g. MySql, H2, SpringSecurity)
https://tweaver.vercel.app 배포 환경에서 발생하였습니다.

**Comment by eod940** [comment]
**문제 원인**
- ChatRoomController 의 117번째 줄 로직에서 발생

백엔드 서버 코드에서 여행그룹 식별자와 채팅룸 식별자를 구분하지 않고 사용해서 일어난 현상입니다.

배포 서버 이전에 따른 DB 마이그레이션 작업 중 trip_group 테이블에서 데이터들의 id가 전부 +1 이 된 상태로 DB에 저장이 되었습니다. 
문제가 된 코드에서는 trip_group_id와 chat_room_id가 혼용되어 사용되었습니다. 문제가 된 로직은 다음과 같습니다.
- chat_room을 찾을때 trip_group_id로 찾음 
- trip_group_id가 전부 +1 되어서 chat_room_id가 +1 되어서 찾아짐 **→ 문제 발생!!**
- 원래는 chat_room_id로 찾았어야 했는데 trip_group_id로 찾아서 이런 문제가 발생함
 
현재 문제가 된 로직을 확인후 수정중입니다.

**Comment by YujinJI** [comment]
확인했습니다!! 정상 작동합니다 :)
