### ISSUE TITLE
[011-CUSTOMEXCEPION] 커스텀 익셉션 공통 반환값 설정

### ISSUE THREAD

**Issue by wooooozin** [ValueWith/ValueWith_BE#18]
**이슈 사항**
- API 응답 성공시에는 상황에 맞는 Response 객체 생성 후 반환하는 것으로 결정한데 반해
에러 처리의 경우 공통된 반환값을 가지는게 좋을것 같아
아래와 같은 응답 형식으로 공통된 반환 Response를 생성하려 합니다.
피드백 요청 드립니다!

private HttpStatus status; // HTTP 상태 코드
private int statusCode; // HTTP 상태 숫자 코드
private String message; // 메세지
private ErrorCode errorCode; // 내부적으로 사용되는 고유한 오류 코드(Enum)

<img width="663" alt="스크린샷 2023-10-29 오후 1 33 03" src="https://github.com/ValueWith/ValueWith_BE/assets/95316662/b595e8fc-f192-4df5-b64c-58e4dfc59346">

**Comment by eod940** [comment]
errorCode가 어떻게 구성될지는 이야기해봐야 알겠지만 errorCode를 추가로 사용하는건 불필요해보입니다.
errorCode 사용하는 이유를 논의해 본 뒤에 목적에 맞게 에러 response를 세팅해보는게 좋을 것 같습니다.

**Comment by wooooozin** [comment]
> �errorCode가 어떻게 구성될지는 이야기해봐야 알겠지만 errorCode를 추가로 사용하는건 불필요해보입니다. errorCode 사용하는 이유를 논의해 본 뒤에 목적에 맞게 에러 response를 세팅해보는게 좋을 것 같습니다.

-----------------------------------------------------------------------

ErrorCode 는 다음과 같이 작성했습니다.
내부적으로 사용되는 Errorcode 가 불필요하다면 dto 수정만 하면됩니다!

package com.valuewith.tweaver.constants;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
@AllArgsConstructor
public enum ErrorCode {
    NO_FILE_UPLOAD("추가된 파일이 없습니다.", HttpStatus.BAD_REQUEST),
    INVALID_FILE_MEDIA_TYPE("JPG, JPEG, PNG 형식만 가능합니다.", HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    S3_IMAGE_NOT_FOUND("이미지 저장소에서 찾을 수 없습니다.", HttpStatus.NOT_FOUND)
    ;

    private final String description;
    private final HttpStatus httpStatus;

}

수정된 결과 입니다!

<img width="797" alt="스크린샷 2023-10-29 오후 2 17 23" src="https://github.com/ValueWith/ValueWith_BE/assets/95316662/28513ee5-a5bd-4fe9-a37d-b906e2f19e54">

**Comment by eod940** [comment]
넵넵 확인했습니다! 사실 없애자는건 아니었고 ErrorCode를 반환하는 이유에 대해서 이야기 해보고 결정하고 싶다는 뜻이었습니다... ㅎㅎ
신경써주셔서 감사합니다!

**Comment by wooooozin** [comment]
음 그러면 추가하고 일단 PR 보내고 이부분은 더 논의해봅시다 👯
