### ISSUE TITLE
패키지명과 클래스명을 변경해야합니다.

### ISSUE THREAD

**Issue by eod940** [ValueWith/ValueWith_BE#19]
**이슈 사항**
1. [#15] 수정 후 패키지명과 엔티티명이 다릅니다.
- memeber/GroupMember
- user/Member
위와 같이 혼동의 여지가 있어 패키지명 수정도 필요할 것 같습니다.
또한 엔티티명 변경 후 기존의 GroupMember(변경전 Member) 이하 클래스 이름도 전부 리팩토링이 필요해 보입니다.

---

**배경**
1. [#17] 이후 master 브랜치에서 위 사항을 발견했습니다.
2. 회원가입 기능 구현 중 발견했습니다.

**Comment by dodunge** [comment]
맞습니다! 제가 다음 pr보낼때 함께 변경해서 보내도록 하겟습니다!

**Comment by eod940** [comment]
넵 감사합니다!

**Comment by wooooozin** [comment]
확인했습니다 :D
