### ISSUE TITLE
password param 이렇게 보내도 되는건가요?

### ISSUE THREAD

**Issue by eod940** [ValueWith/ValueWith_BE#25]
**이슈 사항**
1. 쟁점
아래 사진처럼 post 요청으로 param에 password 들어가도 될까요?
보안적인 측면에서 괜찮을지 모르겠네요...

<img width="946" alt="Screenshot 2023-10-31 at 11 48 31 AM" src="https://github.com/ValueWith/ValueWith_BE/assets/51254234/eb51f0b3-0b67-4f5d-aec4-2b562b2b2e46">
사진1. swagger에서 확인한 모습

<img width="923" alt="Screenshot 2023-10-31 at 11 51 39 AM" src="https://github.com/ValueWith/ValueWith_BE/assets/51254234/d04a4dc4-8f16-4053-bd26-e6ef7b95c29b">
사진2. postman에서 확인한 모습

---

**배경**
1. 어느 환경(배경)에서 문제가 발생했는지 간략히 적어주세요. (e.g. MySql, H2, SpringSecurity)
필요하다면 배경에 대해 설명해 주세요.

**Comment by wooooozin** [comment]
노출안되는게 좋을 것 같습니다!

**Comment by eod940** [comment]
넵넵 혹시 모르니까 프론트 분들이랑 한 번 상의해보고 이슈 닫겠습니다!

**Comment by wooooozin** [comment]
포스트맨으로 하실때 JSON 형식에 맞춰서 POST 하면 될것같아요!
![image](https://github.com/ValueWith/ValueWith_BE/assets/95316662/0e3bc9c0-9a34-42f6-8afe-305f8d6f1556)

**Comment by eod940** [comment]
넵넵 사실 최초에 RequestBody 어노테이션 추가해서 그 방법으로 구현했었는데 415 에러가 자꾸 뜨더라구요... 해결이 안돼서 지금 이 방법으로 진행하게 되었습니다.

**Comment by wooooozin** [comment]
파일이랑 dto 앞에 requestpart 어노테이션 쓰시면 됩니다

**Comment by eod940** [comment]
넵 RequestPart 방법도 사용해봤는데 동일한 에러가 나더라구요...

**Comment by eod940** [comment]
@wooooozin 님 좋은 방법들 추천해주셔서 감사합니다. ㅠㅠ 삽질을 많이 하게되네요..
Danny멘토님이 https를 사용하면 괜찮다고 하시는 것 같아 이만 이 이슈는 마치려고 합니다!!
계속 신경써주셔서 감사합니다.
