### ISSUE TITLE
로그인 기능 구현 중 기능 고도화에 따라 Member 테이블에 컬럼을 추가해야 할 것 같습니다.

### ISSUE THREAD

**Issue by eod940** [ValueWith/ValueWith_BE#42]
**이슈 사항**
현재 기획에 맞게 로그인 기능을 고도화해야합니다. 본 프로젝트 기획에 따라 Refresh token과 소셜로그인 기능을 추가하게 되었습니다.
이에 따라 기존 Member 테이블에 총 3개의 컬럼을 추가해야 할 필요를 느껴 모두가 검토해주셨으면 합니다.

1. refresh token 컬럼 추가
현재 로그인 기능은 Jwt 토큰 하나를 발급하는 방식으로 구현되어 있습니다. 
이는 발급된 토큰의 유효시간이 지날때 마다 로그인을 해야해 사이트 이용자의 부정적인 경험을 유도합니다.
따라서 이용자의 간편한 로그인 경험을 위해 저희 Member 테이블에 **refresh token 컬럼을 추가**하여 관리하고자 합니다.
    - refresh token은 로그인 후 access token이 만료될 때마다 DB의 값과 비교 후 새로운 access token을 발급하기 위한 토큰입니다.
    - refresh token은 회원가입시 null 상태입니다. 따라서 제약조건을 이야기 해봐야 할 것 같습니다.

2. OAuth2-client 사용에 따른 provider, provider id 컬럼 추가 (2개)
소셜 로그인 기능 구현을 위해 OAuth2-client 라이브러리를 사용할 예정입니다. 기존에는 isSocial 컬럼으로 구분하기로 했으나, 이는 OAuth 라이브러리 사용에는 부적절하다고 판단됩니다.
해당 라이브러리를 사용하게 되면 카카오, 네이버, 구글 등 다양한 소셜로그인 제공자를 명시하게 되어있습니다.
따라서 **기존 isSocial 컬럼을 삭제**하고 **소셜로그인 제공자(provider), 소셜로그인 제공자 키 식별자(provider id) 컬럼을 추가**하여 관리하고자 합니다.
    - provider는 소셜로그인 제공 사이트(카카오, 네이버, ...)를 구분합니다.
    - provider id는 OAuth 로그인 시 키(pk)가 되는 값입니다.
    - 컬럼명은 의미를 전달하기 위해 제가 임의로 정하였으나 변경해도 좋을 것 같습니다. (ex. 로그인 타입, 로그인 제공자, ...)

---

**배경**
#41 PR 병합 전 이슈입니다.

**Comment by wooooozin** [comment]
네 좋습니다!

**Comment by dodunge** [comment]
저도 좋습니다! 근데 소셜 로그인에서 키 식별자라고 하면 어떤것을 말씀 하시는 건가요??

**Comment by eod940** [comment]
> 저도 좋습니다! 근데 소셜 로그인에서 키 식별자라고 하면 어떤것을 말씀 하시는 건가요??

넵 이부분은 OAuth2-client의 작동방식과 연관이 있습니다. Oauth client가 소셜로그인을 제공하는 서버(리소스 서버)에게 Authorization Code를 요청하여 반환되게 되는데, 이 부분에서 provider id(소셜 로그인 제공자 키 식별자)가 필요합니다. 해당 식별자는 OAuth로 로그인을 할때 primary key의 역할을 합니다.

**Comment by eod940** [comment]
설명을 추가 드리면 refresh token은 OAuth2 표준이라고 합니다. (kakao open api에서 확인)

**Comment by eod940** [comment]
pr #47 에서 적용하였습니다.
