### ISSUE TITLE
그룹 모집 등록 요청 시 404 에러 발생

### ISSUE THREAD

**Issue by geniee1220** [ValueWith/ValueWith_BE#59]
**이슈 사항**
1. 문제점 발생
그룹 모집 페이지에서 /groups 로 post 요청 보냈을 때 404 에러가 발생합니다. 

---

**배경**
1. 어느 환경(배경)에서 문제가 발생했는지 간략히 적어주세요. 

tripGroupRequestDto 안에 담기는 내용의 형태는 API 요청서와 동일
<img width="953" alt="image" src="https://github.com/ValueWith/ValueWith_BE/assets/110911811/1b013322-dfe7-4612-867b-55c0949c30e1">

- 로그인 되어 있는 상태
- request url은 /groups , method는 post 
- Request Headers에 Authorization: Bearer `${accessToken}` 존재
- file은 content-Type: multipart/form-data로 전송
- tripGroupRequestDto의 content-type은 applicaton/json으로 지정

<img width="818" alt="image" src="https://github.com/ValueWith/ValueWith_BE/assets/110911811/5a636d9b-6d15-4e50-ac5e-8402a8a53ddb">

**Comment by geniee1220** [comment]
fomData 안에 file과 tripGroupRequestDto 를 담아 전송하고 있습니다 
<img width="527" alt="image" src="https://github.com/ValueWith/ValueWith_BE/assets/110911811/7a2badfa-15ea-42c9-a4ad-f0b9a5345104">

**Comment by dodunge** [comment]
일단 url을 /groups/로 뒤에"/"를 붙여주셔야합니다.
이건 노션에서 우진님께서 말씀해주신 것 처럼 추후에 수정하도록겠습니다!
url만 바꾸셔서도 에러가 나시면 다시 말씀해 주세요! 원인을 찾고 수정하도록 하겠습니다!

**Comment by geniee1220** [comment]
/groups/로 요청하니 400에러로 바뀌었습니다! (동일 환경에서 진행)

테스트한 내용입니다
tripDate, dueDate 를 string 타입, Date 타입으로 각각 전송(400) 
위 모든 타입에 header에 토큰 타입 빼고 전송 (#60) (400)

**Comment by dodunge** [comment]
#62 으로 file을 null값을 받을 수 있도록 에러 해결 완료
