### ISSUE TITLE
내 그룹 조회 시, Authorization 500 에러 발생

### ISSUE THREAD

**Issue by geniee1220** [ValueWith/ValueWith_BE#60]
**이슈 사항**
1. 문제점 발생
마이 라운지 그룹 조회(내가 만든 그룹, 참여중인 그룹, 대기중인 그룹) 시 500 에러가 발생 

---

**배경**
1. 어느 환경(배경)에서 문제가 발생했는지 간략히 적어주세요.

- 테스트 URL
  - /groups/list/my-list?status=leader (pending, approved, leader)

현재는 헤더에 Authorization에 Bearer ${accessToken}로 명시하여 보내주고 있는데 Bearer 키워드가 있을 때 500에러가 발생합니다 
Authorization에 JWT Keyword를 Bearer로 알고 있어서 이렇게 처리했는데 혹시 토큰 타입이 어떻게 될까요?

**Comment by geniee1220** [comment]
추가로, API 명세서에서는 status에 대한 params만 명시되어 있어서, paging 처리가 되어있는지 확인 부탁드립니다

**Comment by wooooozin** [comment]
> 추가로, API 명세서에서는 status에 대한 params만 명시되어 있어서, paging 처리가 되어있는지 확인 부탁드립니다

안녕하세요! 나의 그룹 조회에는 따로 페이징 처리가 되어있지 않습니다.
화면 설계상 그냥 하단으로 쭉 나열하는 걸로 확인해서 페이징 처리 필요하시면 말씀해주세요!

**Comment by eod940** [comment]
> **이슈 사항**
> 
> 1. 문제점 발생
>    마이 라운지 그룹 조회(내가 만든 그룹, 참여중인 그룹, 대기중인 그룹) 시 500 에러가 발생
> 
> **배경**
> 
> 1. 어느 환경(배경)에서 문제가 발생했는지 간략히 적어주세요.
> 
> * 테스트 URL
>   
>   * /groups/list/my-list?status=leader (pending, approved, leader)
> 
> 현재는 헤더에 Authorization에 Bearer ${accessToken}로 명시하여 보내주고 있는데 Bearer 키워드가 있을 때 500에러가 발생합니다 Authorization에 JWT Keyword를 Bearer로 알고 있어서 이렇게 처리했는데 혹시 토큰 타입이 어떻게 될까요?

현재 인증 부분에서 `Bearer ` 문자열 파싱을 담당하는 부분이 빠져서 그런 것 같습니다. 수정 후 다시 멘션드리겠습니다.

**Comment by geniee1220** [comment]
@wooooozin 나의 그룹 조회에 페이징 처리 필요할 것 같습니다!

**Comment by wooooozin** [comment]
> @wooooozin 나의 그룹 조회에 페이징 처리 필요할 것 같습니다!

넵! 8개씩 보여지도록 할게요

**Comment by eod940** [comment]
#70 PR에서 Token관련 이슈 대응했습니다.
