### ISSUE TITLE
그룹 모집 후 내 그룹 조회 시, 내가 만든 그룹이 참여중인 그룹에도 보이는 문제 

### ISSUE THREAD

**Issue by geniee1220** [ValueWith/ValueWith_BE#63]
**이슈 사항**
1. 문제점 발생
그룹 모집 이후, 마이라운지 - 그룹 관리에서 확인해보면 내가 만든 그룹이 참여중인 그룹에도 동일하게 보여집니다. 
'내가 만든 그룹'은 내가 그룹을 생성했을 때, '참여중인 그룹'은 내가 그룹장은 아니고 groupMembers에 있을 때 받아와야 할 것 같습니다

---

**배경**
1. 어느 환경(배경)에서 문제가 발생했는지 간략히 적어주세요.
Chormium 엔진 브라우저 모두 동일하게 발생

**Comment by dodunge** [comment]
이문제는 그룹 등록 처리시에 그룹장을 groupMember에 등록하는 처리가 있었어서 조회부분에서 잘못 된 값이 나간것 같습니다! 
아마 지금까지 있는 데이터들은 다 잘못 나올것 같은데
이번에 #62 PR 여기서 해당 로직을 수정했기 때문에 merge하고 서버에 적용해 주시면 이 부분은 해결 될 것 같습니다!
#62 PR 서버에 적용하고 다시 테스트 해보면 좋을 것 같아요!!

**Comment by dodunge** [comment]
#62 에서 그룹 등록시에 groupMember 등록을 제거하여서 해당 문제 해결 완료
