### ISSUE TITLE
필터링 기본값에서 마지막 페이지의 데이터를 불러오지 못하는 이슈

### ISSUE THREAD

**Issue by YujinJI** [ValueWith/ValueWith_BE#66]
**이슈 사항**
1. 문제점 발생
`http://localhost:5173/group?page=1&status=all&area=all&sort=latest&title=`
status, area, sort, title이 기본값인 데이터를 불러오는 중, 마지막 페이지의 데이터를 불러오지 못합니다.
현재는 4페이지까지 존재, 1, 2, 3 페이지는 데이터를 잘 불러오나 4페이지 진입 시 에러 발생합니다. (Error Code: 500)
이전에 2페이지까지 존재했을 때에는 1, 2페이지는 잘 불러오나 2페이지 진입 시 에러 발생했습니다.
area=seoul인 경우, 현재 3페이지 존재하며 1, 2, 3페이지 데이터 잘 불러와집니다.
---

**배경**
1. 어느 환경(배경)에서 문제가 발생했는지 간략히 적어주세요. (e.g. MySql, H2, SpringSecurity)
필요하다면 배경에 대해 설명해 주세요.

**Comment by wooooozin** [comment]
해당 버그 수정해서 오늘 중으로 업데이트 하겠습니다.
지난번 첫페이지 1 부터 시작하는데 있어 수정이 필요할것 같습니다 
확인 및 수정하고 다시 코멘트 드리겠습니다!

**Comment by wooooozin** [comment]
임의로 데이터 생성하면서 created_time이 누락되어 발생한 문제입니다.
데이터 수정으로 해당 응답 정상적으로 확인했습니다.
